StackedDeck/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StackedDeck.Models;
using StackedDeck.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace StackedDeck.Controllers
{
    [Authorize]
    public class GameController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        public static Stack<Card> Cards = Deck.NewDeck();
        public static Stack<Card> DealerHand = new Stack<Card>();
        public static Stack<Card> PlayerHand = new Stack<Card>();
        public static Card FaceDownCard;
        public static Double DealerHandValue;
        public static Double PlayerHandValue;
        public static Double BetAmount;

        public ActionResult Play()
        {
            var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            var user = UserManager.FindByName(User.Identity.GetUserName());

            if (user.Credits < 1)
            {
                return RedirectToAction("Credit", "Home");
            }

            PlayViewModel viewModel = new PlayViewModel();
            viewModel.Credits = Math.Round(user.Credits, 2);
            return View(viewModel);
        }

        // New Game
        public void NewGame()
        {
            Cards.Clear();
            DealerHand.Clear();
            PlayerHand.Clear();
            DealerHandValue = 0;
            PlayerHandValue = 0;
            Cards = Deck.NewDeck();
        }

        // Deal hand
        [HttpPost]
        public ActionResult DealHand(double Bet)
        {
            var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            var user = UserManager.FindByName(User.Identity.GetUserName());
            user.Credits -= Math.Round(Bet, 2);
            BetAmount = Math.Round(Bet, 2);
            UserManager.Update(user); // remove bet amount from user credits
            FaceDownCard = Cards.Pop();
            CardViewModel viewModel = new CardViewModel();
            DealerHand.Push(Cards.Pop());
            DealerHand.Push(new Card(FaceDownCard.Value, "", "card_back.png"));
            PlayerHand.Push(Cards.Pop());
            PlayerHand.Push(Cards.Pop());
            viewModel.DealerHand = DealerHand;
            viewModel.PlayerHand = PlayerHand;
            ViewBag.Ace = false;

            foreach (var Card in DealerHand)
            {
                DealerHandValue += Card.Value;
            }

            foreach (var Card in PlayerHand)
            {
                if (Card.Value == 1)
                {
                    ViewBag.Ace = true;
                    ViewBag.Soft = true;
                }
                PlayerHandValue += Card.Value;
            }
            ViewBag.Hand = PlayerHandValue;
            return PartialView("handPartial", viewModel);
        }

        // Get card
        [HttpGet]
        public ActionResult Hit(Nullable<bool> Soft)
        {
            CardViewModel viewModel = new CardViewModel();
            PlayerHandValue += Cards.Peek().Value;
            ViewBag.Ace = false;
            PlayerHand.Push(Cards.Pop());
            foreach (var Card in PlayerHand)
            {
                //checking for aces
                if (Card.Value == 1)
                {
                    ViewBag.Ace = true;
                    ViewBag.Soft = (Soft == null) ? true : Soft;
                }
            }
            viewModel.PlayerHand = PlayerHand;
            viewModel.DealerHand = DealerHand;
            ViewBag.Hand = PlayerHandValue;
            return PartialView("playerHandPartial", viewModel);
        }

        // Stand
        [HttpGet]
        public ActionResult Stand()
        {
            CardViewModel viewModel = new CardViewModel();
            DealerHand.Pop();
            DealerHand.Push(FaceDownCard);

            while (DealerHandValue < 17)
            {
                DealerHandValue += Cards.Peek().Value;
                DealerHand.Push(Cards.Pop());
            }
            viewModel.DealerHand = DealerHand;
            ViewBag.DealerHand = DealerHandValue;
            return PartialView("dealerHandPartial", viewModel);
        }

        // Toggle Ace Value
        [HttpPost]
        public ActionResult Ace(bool Soft)
        {
            CardViewModel viewModel = new CardViewModel();
            ViewBag.Hand = Soft ? PlayerHandValue += 10 : PlayerHandValue -= 10 ;
            viewModel.PlayerHand = PlayerHand;
            ViewBag.Soft = !Soft;
            ViewBag.Ace = true;
            return PartialView("playerHandPartial", viewModel);
        }

        // Hit Result
        public string HitResult()
        {
            if (PlayerHandValue > 21)
            {
                return "<div class='text-danger'>Lose</div>";
            }
            else
            {
                return "";
            }
        }

        // Get Result
        public string Result()
        {
            var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            var user = UserManager.FindByName(User.Identity.GetUserName());

            if ((DealerHandValue <= 21 && PlayerHandValue < DealerHandValue) || (PlayerHandValue > 21 && DealerHandValue <= 21))
            {
                return "<div class='text-danger'>Lose</div>";
            }
            else if ((PlayerHandValue <= 21 && PlayerHandValue > DealerHandValue) || (DealerHandValue > 21 && PlayerHandValue <= 21))
            {
                user.Credits += BetAmount * 2;
                UserManager.Update(user);
                return "<div class='text-success'> Win " + (BetAmount * 2).ToString("C") + "</div>";
            }
            else
            {
                user.Credits += BetAmount;
                UserManager.Update(user);
                return "Tie";
            }
        }
    }
}

StackedDeck/Views/Shared/Info.cshtml
@{
    ViewBag.Title = "Info";
}
<div class="container margin-top-sm">
    <h2>Email Confirmation</h2>
    <h3>@ViewBag.Message</h3>
</div>

StackedDeck/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/bundles/css")
    @Styles.Render("https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css")
    <link href='https://fonts.googleapis.com/css?family=Raleway:700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Julius+Sans+One' rel='stylesheet' type='text/css'>
    @Scripts.Render("~/bundles/modernizr")
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @if (Request.IsAuthenticated)
                {
                    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm"}))
                    {
                        @Html.AntiForgeryToken()
                        <a href="javascript:document.getElementById('logoutForm').submit()" class="navbar-brand">Logout</a>
                    }
                }
                else {
                    @Html.ActionLink("Login", "Login", "Account", new { area = "" }, new { @class = "navbar-brand" })
                }              
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-left">
                    @if (User.IsInRole("Admin"))
                    {
                        <li><a href="/Admin/Admin"><i class="fa fa-users fa-lg"></i></a></li>
                    }
                    @if (Request.IsAuthenticated)
                    {
                        <li><a href="/Manage/Index"><i class="fa fa-user fa-lg"></i></a></li>
                        <li><a href="/Discussion/Discussion"><i class="fa fa-list-alt fa-lg"></i></a></li>
                        <li><a href="/Message/Messages"><i class="fa fa-comments fa-lg"></i></a></li>
                        <li><a href="/Home/Credit"><i class="fa fa-usd fa-lg"></i></a></li>
                        
                    }
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (Request.IsAuthenticated)
                    {
                        <li><a href="/Manage/Index">@User.Identity.Name</a></li>
                        <li>@Html.ActionLink("Play", "Play", "Game")</li>
                        <li>@Html.ActionLink("Home", "Home", "Home")</li>
                        <li>@Html.ActionLink("How To Play", "HowToPlay", "Home")</li>
                    }
                    else {
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    }
                    <li>@Html.ActionLink("Features", "Features", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </nav>
    @RenderBody()
    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>