StackedDeck/ViewModels/MessageViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using StackedDeck.Models;

namespace StackedDeck.ViewModels
{
    public class MessageViewModel
    {
        public IEnumerable<Message> Messages { get; set; }
    }
}

StackedDeck/Controllers/MessageController.cs
using StackedDeck.ViewModels;
using StackedDeck.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.Owin;
using System.Threading.Tasks;

namespace StackedDeck.Controllers
{
    [Authorize]
    public class MessageController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        // GET: Conversations
        public ActionResult Messages()
        {
            MessageViewModel viewModel = new MessageViewModel();
            string query = "SELECT Sender, COUNT(*) AS Replies FROM dbo.AspNetMessages WHERE Recipient = '" + User.Identity.Name + "' GROUP BY Sender";
            IEnumerable<Message> Messages = db.Database.SqlQuery<Message>(query);
            viewModel.Messages = Messages;
            return View(viewModel);
        }

        // POST: User Conversation
        [HttpPost]
        public ActionResult UserConversation(string Sender)
        {
            MessageViewModel viewModel = GetUserConversation(Sender);
            return PartialView(viewModel);
        }

        // POST: Message Reload
        [HttpPost]
        public ActionResult MessageReload(string Sender)
        {
            MessageViewModel viewModel = GetUserConversation(Sender);
            return PartialView("ConversationPartial", viewModel);
        }

        // GET: User Conversation
        public MessageViewModel GetUserConversation(string Sender)
        {
            MessageViewModel viewModel = new MessageViewModel();
            ViewBag.Sender = Sender;
            string Recipient = User.Identity.Name;
            string query = "SELECT * FROM dbo.AspNetMessages WHERE (Recipient = '" + Recipient + "' AND Sender = '" + Sender + "') OR " +
                            "(Recipient = '" + Sender + "' AND Sender = '" + Recipient + "') ORDER BY MessageDate ASC";
            IEnumerable<Message> Messages = db.Database.SqlQuery<Message>(query);
            viewModel.Messages = Messages;
            return viewModel;
        }

        // POST: New Message
        [HttpPost]
        public async Task<ActionResult> NewMessage(string recipient, string message)
        {
            var user = await UserManager.FindByNameAsync(recipient);
            if (user != null)
            {
                string Sender = User.Identity.Name;
                string query = "INSERT INTO dbo.AspNetMessages (Sender, Recipient, Content, MessageDate) " +
                               "VALUES('" + Sender + "', '" + recipient + "', '" + message + "', GETDATE())";
                db.Database.ExecuteSqlCommand(query);
            }
            return PartialView("ConversationPartial", GetUserConversation(recipient));
        }

        // POST: Search Message
        [HttpPost]
        public ActionResult Search(string search, string mail)
        {
            MessageViewModel viewModel = new MessageViewModel();
            string s = search.ToLowerInvariant();
            string user = User.Identity.Name;
            string query = "SELECT Sender, COUNT(*) AS Replies FROM dbo.AspNetMessages WHERE Recipient = '" + user + "' AND " + "(Sender LIKE '%" + s + "%') GROUP BY Sender";
            IEnumerable<Message> Messages = db.Database.SqlQuery<Message>(query);

            viewModel.Messages = Messages;
            return PartialView("MessagesPartial", viewModel);
        }

    }
}

StackedDeck/Views/Message/ConversationPartial.cshtml
@model StackedDeck.ViewModels.MessageViewModel

@foreach (var m in Model.Messages)
            {
                if (@m.Sender == ViewBag.Sender)
                {
        <div class="row">
            <div class="col-xs-5">
                <h4 class="bubble-left margin-bottom-xs">@m.Sender: @m.Content</h4>
                <h5 class="text-right">@m.MessageDate.ToShortDateString()</h5>
                <h5 class="text-right">@m.MessageDate.ToShortTimeString()</h5>
            </div>
        </div>
    }
    else
    {
        <div class="row">
            <div class="col-xs-offset-7 col-xs-5">
                <h4 class="bubble-right margin-bottom-xs">@m.Content</h4>
                <h5 class="text-right">@m.MessageDate.ToShortDateString()</h5>
                <h5 class="text-right">@m.MessageDate.ToShortTimeString()</h5>
            </div>
        </div>
    }
}

StackedDeck/Views/Message/Messages.cshtml
@model StackedDeck.ViewModels.MessageViewModel

@{
    ViewBag.Title = "Messages";
}

<div class="container margin-top-sm">
    <h2>Messages</h2>
    <hr />
    <div class="panel with-nav-tabs panel-default text-black" id="MessagePanel">
        <div class="panel-heading">
            <ul class="nav nav-tabs">
                <li class="active" id="Conversations"><a href="#ConversationTab" data-toggle="tab">Conversations</a></li>
            </ul>
        </div>
        <div class="panel-body">
            <div class="tab-content">
                <div class="tab-pane fade in active" id="ConversationTab">
                    <div class="row" style="margin-bottom: 10px;">
                        <div class="col-xs-8">
                            @using (Ajax.BeginForm("Search", "Message", new AjaxOptions { HttpMethod = "Post", InsertionMode = InsertionMode.Replace, UpdateTargetId = "ConversationTable" }, new { @class = "form-horizontal", role = "form" }))
                            {
                                <input type="hidden" name="mail" value="inbox" />
                                <div class="input-group">
                                    <input type="text" class="form-control" name="search" placeholder="Search Conversations...">
                                    <span class="input-group-btn">
                                        <button class="btn btn-primary" type="submit"><i class="fa fa-search"></i></button>
                                    </span>
                                </div>
                            }
                        </div>
                        <div class="col-xs-4">
                            <button class="btn btn-primary pull-right" data-toggle="modal" data-target="#NewMessageModal" data-whatever=""><i class="fa fa-pencil fa-lg"></i></button>
                        </div>
                    </div>
                    <div id="ConversationTable">
                        <table class="table table-bordered table-hover text-left">
                            <thead>
                                <tr>
                                    <th>Conversation With</th>
                                    <th class="col-xs-1 text-right">Replies</th>
                                </tr>
                            </thead>
                            <tbody data-link="row" class="rowlink">
                                @foreach (var m in Model.Messages)
                                {
                                    <tr>
                                        <td>@m.Sender@Ajax.ActionLink(" ", "UserConversation", "Message", new { Sender = @m.Sender}, new AjaxOptions { HttpMethod = "Post", InsertionMode = InsertionMode.Replace, UpdateTargetId = "MessagePanel" })</td>
                                        <td class="col-xs-1 text-right">@m.Replies</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    <nav>
                        <ul class="pagination margin-top-none margin-bottom-none" id="message-pagination"></ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="NewMessageModal" tabindex="-1" role="dialog" aria-labelledby="NewMessageModalLabel">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content text-black">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><i class="fa fa-times"></i></span></button>
                    <h4 class="modal-title" id="NewMessageModalLabel">New message</h4>
                </div>
                @using (Ajax.BeginForm("NewMessage", "Message", new AjaxOptions { HttpMethod = "Post", OnComplete = "location.reload()" }, new { @class = "", role = "form", @id = "NewMessageForm" }))
                {
                    <div class="modal-body text-left">
                        <div class="form-group">
                            <label for="recipient-name" class="control-label">To:</label>
                            <input type="text" name="recipient" class="form-control" id="recipient-name">
                        </div>
                        <div class="form-group">
                            <label for="message-text" class="control-label">Message:</label>
                            <input class="form-control" name="message" id="message" style="padding-bottom: 100px; padding-top: 15px;"/>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Send Message</button>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
@Styles.Render("~/Content/panels.css")
@Styles.Render("~/Content/bubbles.css")
@Scripts.Render("~/Scripts/messages.js")
@Scripts.Render("~/Scripts/jasny-bootstrap.min.js")
@Scripts.Render("~/Scripts/jquery.twbsPagination.min.js")

StackedDeck/Views/Message/MessagesPartial.cshtml
@model StackedDeck.ViewModels.MessageViewModel

<table class="table table-bordered table-hover text-left">
    <thead>
        <tr>
            <th>Conversation With</th>
            <th class="col-xs-1 text-right">Replies</th>
        </tr>
    </thead>
    <tbody data-link="row" class="rowlink">
        @foreach (var m in Model.Messages)
        {
            <tr>
                <td>@m.Sender@Ajax.ActionLink(" ", "UserConversation", "Message", new { Sender = @m.Sender }, new AjaxOptions { HttpMethod = "Post", InsertionMode = InsertionMode.Replace, UpdateTargetId = "MessagePanel" })</td>
                <td class="col-xs-1 text-right">@m.Replies</td>
            </tr>
        }
    </tbody>
</table>

StackedDeck/Views/Message/SentMessages.cshtml
@model StackedDeck.ViewModels.MessageViewModel

<table class="table table-bordered table-hover text-left">
    <thead>
        <tr>
            <th class="col-xs-2">To</th>
            <th>Subject</th>
            <th class="col-xs-2 text-right">Date</th>
        </tr>
    </thead>
    <tbody data-link="row" class="rowlink">
        @foreach (var m in Model.Messages)
        {
            <tr>
                <td class="col-xs-2">@m.Recipient</td>
                <td>@m.Subject<a href="#MessageModal" data-toggle="modal" data-target="#MessageModal" data-sender="@m.Sender" data-subject="@m.Subject"></a></td>
                <td class="col-xs-2 text-right">@m.MessageDate.ToString("MMMM dd, yyyy")</td>
            </tr>
        }
    </tbody>
</table>

StackedDeck/Views/Message/UserConversation.cshtml
@model StackedDeck.ViewModels.MessageViewModel

<div class="panel-heading">
    <ul class="nav nav-tabs">
        <li id="Conversations"><a href="/Message/Messages">Conversations</a></li>
        <li class="active" id="Conversations"><a href="#ConversationTab" data-toggle="tab">@ViewBag.Sender</a></li>
    </ul>
</div>
<div class="panel-body">
    <div class="tab-content">
        <div class="tab-pane fade in active" id="ConversationTab">
            @foreach (var m in Model.Messages)
            {
                if (@m.Sender == ViewBag.Sender)
                {
                        <div class="row">
                            <div class="col-xs-5">
                                <h4 class="bubble-left margin-bottom-xs">@m.Sender: @m.Content</h4>
                                <h5 class="text-right">@m.MessageDate.ToShortDateString()</h5>
                                <h5 class="text-right">@m.MessageDate.ToShortTimeString()</h5>
                            </div>
                        </div>
                }
                else
                {
                    <div class="row">
                        <div class="col-xs-offset-7 col-xs-5">
                            <h4 class="bubble-right margin-bottom-xs">@m.Content</h4>
                            <h5 class="text-right">@m.MessageDate.ToShortDateString()</h5>
                            <h5 class="text-right">@m.MessageDate.ToShortTimeString()</h5>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
</div>
<div class="panel-footer padding-bottom-sm">
    @using (Ajax.BeginForm("NewMessage", "Message", new AjaxOptions { HttpMethod = "Post", InsertionMode = InsertionMode.Replace, UpdateTargetId = "ConversationTab", OnSuccess = "clearMessage" }, new { @class = "form-horizontal text-right" }))
    {
        <div class="form-group">
            <div class="col-xs-12">
                <input name="message" class="form-control" style="padding-bottom: 100px; padding-top: 15px;" required="required" id="NewMessageInput"/>
            </div>
        </div>
        <input type="hidden" name="recipient" id="recipient" value="@ViewBag.Sender" />
        <input type="submit" class="btn btn-primary pull-right" value="Send" />
    }
</div>
@Scripts.Render("~/Scripts/message-reload.js")